language: cpp
install:
  - sudo apt-get install libblas3gf libblas-dev
  - sudo pip install cpp-coveralls
script:
  - ./setup --cxx=g++ --coverage --type=debug
  - cd build
  - make
  - ./unit_tests
  - coveralls --exclude lib --exclude tests
