language: cpp
install:
  - sudo pip install cpp-coveralls
  - sudo pip install pytest
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9 valgrind
  - sudo apt-get install libblas3gf libblas-dev
script:
  - python setup.py --cxx=g++ --coverage --type=debug
  - cd build
  - make
  - make test
  - valgrind -v ./test_lda_energy
  - cd ..
  - py.test -vv test/test.py build
after_success:
  - coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"
