language: cpp

sudo: false

os:
  - linux
# - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gfortran-7
      - libblas-dev
      - libblas3gf
      - python-virtualenv

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      virtualenv venv
      source venv/bin/activate
      curl https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.tar.gz | tar xvz
      export PATH=$PWD/cmake-3.10.1-Linux-x86_64/bin:$PATH
      export LD_LIBARY_PATH=$PWD/cmake-3.10.1-Linux-x86_64/lib:$LD_LIBRARY_PATH
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install gcc
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install -r requirements.txt
  - export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

script:
  - git submodule update --init --recursive
  - if test ${TRAVIS_OS_NAME} = linux; then ./setup --cxx=g++-7 --fc=gfortran-7 --coverage --type=debug;
                                       else ./setup --cxx=g++-7 --fc=gfortran-7            --type=debug; fi
  - cd build
  - make
  - make test
  - cd ..
  - pycodestyle --ignore=E501 test/test.py
# deactivated until xcint is refactored
# then there will be no need for BLAS which currently does not link
# - PYTHONPATH="build:build/numgrid/src/numgrid-build" pytest -vv test/test.py

after_success:
  - if test ${TRAVIS_OS_NAME} = linux; then coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"; fi

notifications:
  email: false
