language: cpp

sudo: false

os:
  - linux
# - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gfortran-4.9
      - valgrind
      - cmake
      - libblas-dev
      - libblas3gf
      - python-virtualenv

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      virtualenv venv
      source venv/bin/activate
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake python valgrind gcc
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install -r requirements.txt
  - export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH

script:
  - git submodule update --init --recursive
  - if test ${TRAVIS_OS_NAME} = linux; then ./setup --cxx=g++ --fc=gfortran-4.9 --coverage --type=debug;
                                       else ./setup --cxx=g++ --fc=gfortran                --type=debug; fi
  - cd build
  - make
  - make test
  - cd ..
  - pep8 --ignore=E501 test/test.py
# - py.test -vv test/test.py build

after_success:
  - if test ${TRAVIS_OS_NAME} = linux; then coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"; fi

notifications:
  email: false
