language: cpp
install:
  - sudo pip install cpp-coveralls
  - sudo pip install pytest
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9 valgrind
  - sudo apt-get install libblas3gf libblas-dev
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
script:
  - ./configure.py --mpi --cc=mpicc --cxx=mpicxx build_mpi
  - cd build_mpi
  - make
  - make test
  - cd ..
  - ./configure.py --cxx=g++ --coverage --type=debug
  - cd build
  - make
  - make test
  - cd ..
  - py.test -vv test/test.py build
after_success:
  - coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*generated.*" -E ".*test_.*"
